name: CI/CD Pipeline

on:
  push:
    branches:
      - deploy-to-ec2


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t intergrationninjas/reactjs-app .

    - name: Publish image to dockerhub
      run: docker push your-docker intergrationninjas/reactjs-app:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    
